### ISSUE TITLE
BurnerWallertConnector losing connection after refresh the page

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-connectors#133]

**Comment by mvares** [comment]
Hey @LuizAsFight! I'm not sure, but I think we might be able to resolve this by using `localStorage`.

**Comment by mvares** [comment]
The `BurnerWalletConnector` is losing its connection after a page refresh because the state of the `burnerWallet` and `burnerWalletProvider` is not being persisted between sessions.

**Comment by LuizAsFight** [comment]
the `localStorage` is already used if the user don't override the `storage` when creating the connector

it is used to persist the pkey of the wallet which should be enough to recreate the correct wallet after refresh

It's a great idea to persist the `providerUrl` also, this way we can recreate the correct provider after refresh also

**Comment by mvares** [comment]
> the `localStorage` is already used if the user don't override the `storage` when creating the connector
> 
> it is used to persist the pkey of the wallet which should be enough to recreate the correct wallet after refresh
> 
> It's a great idea to persist the `providerUrl` also, this way we can recreate the correct provider after refresh also

@LuizAsFight, are you speaking about `burnerWalletProviderUrl`?

**Comment by mvares** [comment]
> the `localStorage` is already used if the user don't override the `storage` when creating the connector
> 
> it is used to persist the pkey of the wallet which should be enough to recreate the correct wallet after refresh
> 
> It's a great idea to persist the `providerUrl` also, this way we can recreate the correct provider after refresh also

Looks great! I'll send a PR.
