### ISSUE TITLE
Solana Connectors is showing up below the page window in mobile

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-connectors#175]
![Image](https://github.com/user-attachments/assets/e62326f4-c621-496a-8b8c-513af34eb984)

**Comment by helciofranco** [comment]
I couldn't reproduce that issue, even using Telegram.
Waiting on more feedback to go further.

<video src="https://github.com/user-attachments/assets/fe8271ff-13e9-4d8d-a5a0-5941592fdd8e" />

Tagging as blocked for now.

**Comment by bradstevens1** [comment]
Are you able to connect your wallet now ?

**Comment by helciofranco** [comment]
@bradstevens1 yes, no problem on my end, did you get any issues?

**Comment by bradstevens1** [comment]
No just asking if you did cause i got something like this and got to contact the support team and they’re are able to solved it

**Comment by helciofranco** [comment]
@bradstevens1 oh I see, what issue did you report? is in solana connector?

**Comment by bradstevens1** [comment]
Yes but since you’ve been able to connect your wallet think you don’t have any problem with it anymore?
