### ISSUE TITLE
when connecting , then disconnecting, then connecting again, the connect popup doesnt close

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuel-connectors#300]

**Comment by helciofranco** [comment]
@LuizAsFight How did you reproduce this issue?
I've tried several times, and I could close the popup in any situation.

| 📷  Demo |
| --- |
| <video src="https://github.com/user-attachments/assets/f520ce61-4c4c-48e5-9e1a-1cec37463f5b" /> |
