### ISSUE TITLE
strange behaviour connecting to Metamask

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-connectors#35]
when connecting to `Metamask`, it wants to switch to `mainnet`, I say no by pressing `Cancel`, The connector shows that nothing is connected until I hit `reload` and then it shows metamask is connected with a Balance of `0.002 ETH` - and where does this balance come from?

https://github.com/FuelLabs/fuel-connectors/assets/114662397/f8943ad3-aaaf-4f35-982c-0424972c096d

Expected:

1. Should not have to reload to show the Connector is connected to Metamask
2. Should be able to connect to either `Sepolia` (or other testnets) as well as `mainnet`
3. In a previous test, when it was connected to Metamask `mainnet`, I clicked on `Get coins` - so that might be where the `0.002 ETH` comes from, but should it show that balance when it's connected to `Sepolia` afterwards?

**Comment by luizstacio** [comment]
The network in this case do not affect the connector, as the connector is using the fuel network and the metamask is used just to sign messages to authorize the tx's on fuel. I think it requires a bit more explanation, on how it works.
