### ISSUE TITLE
Can create a transaction with an empty receiver address

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-connectors#37]
It's possible to delete the address from the `Receiver address` field, but the `Connector` still picks up an address and we can go ahead and create a transaction

https://github.com/FuelLabs/fuel-connectors/assets/114662397/156979bc-280b-4b7d-b8f1-e7ec517b39d4

The expectation is that there's an info message asking the user to put a Bech32 address into the `Receiver address` field

**Comment by luizstacio** [comment]
Ensure field is not empty and is valid probably linked to #38
