### ISSUE TITLE
B256 address should state Bech32 address

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-connectors#38]
If you put an invalid address into the `Receiver address` field, the error message contains `Invalid B256 Address` - should it say `Invalid Bech32 address`?

https://github.com/FuelLabs/fuel-connectors/assets/114662397/d45fb971-4996-444b-864c-91fd7b6d7848

**Comment by luizstacio** [comment]
We should add a validation on the input and just say `invalid address`.
