### ISSUE TITLE
Tech debt: Connector using functions that will be deprecated

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-connectors#41]
In the dev tools, it can be observed that the code is using a function that will be deprecated, `getProvider`, and that `getWallet` should be used instead.

This happens when the users clicks on the `Transfer 0.0001 ETH` button

![Image](https://github.com/FuelLabs/fuel-connectors/assets/114662397/24f9a8d4-0b0d-4bc2-adec-fbc8e540efcd)

**Comment by luizstacio** [comment]
This is expected behavior we want to ensure, people are using it, but aware it's going to be removed in the future.
