### ISSUE TITLE
Metamask Connect option duplicated

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-connectors#53]
Metamask can be selected under both `Connect Wallet` and in the nested option, `Ethereum Wallets`

https://github.com/FuelLabs/sway/assets/114662397/20d88190-1c48-47cd-8566-16692b933cf4

Should we see it under `Ethereum Wallets` only?

**Comment by luizstacio** [comment]
Both options are possible, we are not going to market `MetaMask Connector` anymore, but if a application wants to use it would be replicated. But would not be issue.
