### ISSUE TITLE
Remove dependencies on `@fuel-ts/fuel-core`

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuel-connectors#84]
As part of https://github.com/FuelLabs/fuels-ts/pull/2143. We have internalised `@fuel-ts/fuel-core`, therefore they won't be available via NPM once we release.

- Remove the dependency on **`@fuel-ts/fuel-core`**.
- Ensure the developer workflow works as expected (build, test, CI).

> Note: this PR has not yet been merged and this is a pre-emptive measure to ensure we're not a blocker.

**Comment by helciofranco** [comment]
@petertonysmith94 did you guys also moved to the pipeline in the SDK to handle cases like this?
and regarding running locally, what are the needed changes?

**Comment by petertonysmith94** [comment]
I have unassigned myself for now and closed the PR:

- https://github.com/FuelLabs/fuel-connectors/pull/89

Please let me know when you come round to the upgrade and I'll more than willing to assist.

**Comment by LuizAsFight** [comment]
I just checked your pr and it's looking good @petertonysmith94 thanks for helping, we're [upgrading sdk](https://github.com/FuelLabs/fuel-connectors/pull/158) version as of now

**Comment by petertonysmith94** [comment]
@LuizAsFight you're most welcome, I'm around if you need any assistance [upgrading the SDK](https://github.com/FuelLabs/fuel-connectors/pull/158).
(I'm sure you've got it though 🚀 )
